/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 08 17:50:08 GMT 2025
 */

package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.WeightHelper;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class WeightHelper_ESTest extends WeightHelper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(100.0, 30.0);
      assertEquals("Obese", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      // Undeclared exception!
      try { 
        weightHelper0.calculateBMI(0.0, 14.480053150261732);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Height must be > 0 and weight must be >= 0
         //
         verifyException("org.example.WeightHelper", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      double double0 = weightHelper0.calculateBMI(100.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      // Undeclared exception!
      try { 
        weightHelper0.getBMICategory((-1210.39488), (-1210.39488));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Height must be > 0 and weight must be >= 0
         //
         verifyException("org.example.WeightHelper", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      double double0 = weightHelper0.calculateBMI(690.605199872436, 690.605199872436);
      assertEquals(14.480053150261732, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(1.0, 414.9769804086198);
      assertEquals("Obese", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(100.0, 25.0);
      assertEquals("Overweight", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(765.5781967194691, 25.0);
      assertEquals("Underweight", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      // Undeclared exception!
      try { 
        weightHelper0.calculateBMI(3185.65728, (-1271.7));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Height must be > 0 and weight must be >= 0
         //
         verifyException("org.example.WeightHelper", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(100.0, 18.5);
      assertEquals("Normal weight", string0);
  }
}
